spring.application.name=employee-workflow-system

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/employee_workflow_system
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF
logging.level.org.springframework=ERROR
spring.main.banner-mode=off